# Generated by scripts/setup.sh - DO NOT EDIT MANUALLY
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

set(CMAKE_C_COMPILER aarch64-tdx-linux-gcc)
set(CMAKE_CXX_COMPILER aarch64-tdx-linux-g++)
set(CMAKE_SYSROOT /opt/tdx-xwayland-rt/7.4.0/sysroots/armv8a-tdx-linux)

set(CMAKE_C_FLAGS " -O2 -pipe -g -feliminate-unused-debug-types " CACHE STRING "" FORCE)
set(CMAKE_CXX_FLAGS " -O2 -pipe -g -feliminate-unused-debug-types " CACHE STRING "" FORCE)
set(CMAKE_EXE_LINKER_FLAGS "-Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed  -Wl,-z,relro,-z,now" CACHE STRING "" FORCE)

set(CMAKE_MAKE_PROGRAM /usr/bin/make CACHE FILEPATH "Make program")

set(CMAKE_C_COMPILER_WORKS TRUE)
set(CMAKE_CXX_COMPILER_WORKS TRUE)
