#!/bin/bash
# scripts/setup.sh
set -e

echo "🔍 Checking for Yocto SDK environment variables..."

if [ -z "$CC" ] || [ -z "$CXX" ] || [ -z "$SDKTARGETSYSROOT" ]; then
    echo "❌ Environment variables CC, CXX, or SDKTARGETSYSROOT are not set."
    echo "   Please source your Yocto SDK environment script first, e.g.:"
    echo "   source /opt/tdx-xwayland-rt/7.4.0/environment-setup-armv8a-tdx-linux"
    exit 1
fi

echo "✅ Environment variables found."
echo "🛠️  CC     : $CC"
echo "🛠️  CXX    : $CXX"
echo "📂 Sysroot : $SDKTARGETSYSROOT"

CC_BARE=$(echo $CC | awk '{print $1}')
CXX_BARE=$(echo $CXX | awk '{print $1}')

# Try to find the SDK's make
if [ -n "$OECORE_NATIVE_SYSROOT" ] && [ -f "$OECORE_NATIVE_SYSROOT/usr/bin/make" ]; then
    MAKE_PATH="$OECORE_NATIVE_SYSROOT/usr/bin/make"
elif [ -n "$OECORE_NATIVE_SYSROOT" ] && [ -f "$OECORE_NATIVE_SYSROOT/bin/make" ]; then
    MAKE_PATH="$OECORE_NATIVE_SYSROOT/bin/make"
else
    MAKE_PATH="/usr/bin/make"
    echo "⚠️  SDK make not found. Using system make at $MAKE_PATH"
fi

echo "🔨 Make path : $MAKE_PATH"

cat > toolchain.cmake << EOF
# Generated by scripts/setup.sh - DO NOT EDIT MANUALLY
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

set(CMAKE_C_COMPILER $CC_BARE)
set(CMAKE_CXX_COMPILER $CXX_BARE)
set(CMAKE_SYSROOT $SDKTARGETSYSROOT)

set(CMAKE_C_FLAGS "$CFLAGS" CACHE STRING "" FORCE)
set(CMAKE_CXX_FLAGS "$CXXFLAGS" CACHE STRING "" FORCE)
set(CMAKE_EXE_LINKER_FLAGS "$LDFLAGS" CACHE STRING "" FORCE)

set(CMAKE_MAKE_PROGRAM $MAKE_PATH CACHE FILEPATH "Make program")

set(CMAKE_C_COMPILER_WORKS TRUE)
set(CMAKE_CXX_COMPILER_WORKS TRUE)
EOF

echo "✅ toolchain.cmake generated successfully."
echo ""
echo "🎉 Setup complete! You can now build the application using:"
echo "   cmake --preset default"
echo "   cmake --build --preset default"